# Configuration File for Hardware-Check

# max CPU-temperature in ° Celsius, must be a floating point number
maxCpuTemp: 80.0
# minutes between two checks, must be an integer
checkInterval: 10
# whom to warn
telegramChatID: '-559789286'
# Telegram API URL
telegramApiUrl: 'https://api.telegram.org/'
# Telegram API Key
telegramToken: 'bot1842158365:AAGWo3CqoVYYTBRN7uETQ8axicrgSF4ipFU'
